In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pd.read_csv("bank.csv")

In [7]:
df.head() 
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 1 columns):
 #   Column                                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                                      --------------  -----
 0   age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit  11162 non-null  object
dtypes: object(1)
memory usage: 87.3+ KB

       age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
count                                               11162
unique                                              11162
top     59,admin.,married,secondary,no,2343,yes,no,unk...
freq                                                    1

In [9]:
df.isnull().sum()
df.duplicated().sum()
df.nunique()

age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit    11162
dtype: int64

In [17]:
df.columns.tolist()

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'deposit']

In [19]:
df["deposit"].value_counts()

deposit
no     5873
yes    5289
Name: count, dtype: int64

In [21]:
for col in df.select_dtypes(include="object").columns:
    print(col)
    print(df[col].unique())
    print("-------------")

job
['admin.' 'technician' 'services' 'management' 'retired' 'blue-collar'
 'unemployed' 'entrepreneur' 'housemaid' 'unknown' 'self-employed'
 'student']
-------------
marital
['married' 'single' 'divorced']
-------------
education
['secondary' 'tertiary' 'primary' 'unknown']
-------------
default
['no' 'yes']
-------------
housing
['yes' 'no']
-------------
loan
['no' 'yes']
-------------
contact
['unknown' 'cellular' 'telephone']
-------------
month
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
-------------
poutcome
['unknown' 'other' 'failure' 'success']
-------------
deposit
['yes' 'no']
-------------

In [23]:
df.shape

(11162, 17)

In [25]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [27]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [29]:
df.duplicated().sum()

0

In [31]:
df = df.drop_duplicates()

In [33]:
for col in df.select_dtypes(include='object').columns:
    print(col)
    print(df[col].value_counts())
    print("="*50)

job
job
management       2566
blue-collar      1944
technician       1823
admin.           1334
services          923
retired           778
self-employed     405
student           360
unemployed        357
entrepreneur      328
housemaid         274
unknown            70
Name: count, dtype: int64
==================================================
marital
marital
married     6351
single      3518
divorced    1293
Name: count, dtype: int64
==================================================
education
education
secondary    5476
tertiary     3689
primary      1500
unknown       497
Name: count, dtype: int64
==================================================
default
default
no     10994
yes      168
Name: count, dtype: int64
==================================================
housing
housing
no     5881
yes    5281
Name: count, dtype: int64
==================================================
loan
loan
no     9702
yes    1460
Name: count, dtype: int64
==================================================
contact
contact
cellular     8042
unknown      2346
telephone     774
Name: count, dtype: int64
==================================================
month
month
may    2824
aug    1519
jul    1514
jun    1222
nov     943
apr     923
feb     776
oct     392
jan     344
sep     319
mar     276
dec     110
Name: count, dtype: int64
==================================================
poutcome
poutcome
unknown    8326
failure    1228
success    1071
other       537
Name: count, dtype: int64
==================================================
deposit
deposit
no     5873
yes    5289
Name: count, dtype: int64
==================================================

In [35]:
df.replace("unknown", np.nan, inplace=True)

In [37]:
df.isnull().sum()

age             0
job            70
marital         0
education     497
default         0
balance         0
housing         0
loan            0
contact      2346
day             0
month           0
duration        0
campaign        0
pdays           0
previous        0
poutcome     8326
deposit         0
dtype: int64

In [39]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[18, 25, 35, 45, 55, 65, 100],
    labels=["18-25", "26-35", "36-45", "46-55", "56-65", "65+"]
)

In [41]:
df["balance_segment"] = pd.cut(
    df["balance"],
    bins=[-10000, 0, 1000, 5000, 10000, 100000],
    labels=["Negative", "Low", "Medium", "High", "Very High"]
)

In [43]:
df["loan_status"] = df["loan"] + "_" + df["housing"]

In [45]:
df["deposit"].value_counts()
df["deposit"].value_counts(normalize=True) * 100
df["balance"].mean()
df["age"].mean()

41.231947679627304

In [47]:
df.to_csv("bank_cleaned.csv", index=False)

In [49]:
import sqlite3

In [51]:
conn = sqlite3.connect("finsight_bank.db")

In [53]:
df.to_sql("bank_customers", conn, if_exists="replace", index=False)

11162

In [55]:
pd.read_sql("SELECT * FROM bank_customers LIMIT 5", conn)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit,age_group,balance_segment,loan_status
0,59,admin.,married,secondary,no,2343,yes,no,None,5,may,1042,1,-1,0,None,yes,56-65,Medium,no_yes
1,56,admin.,married,secondary,no,45,no,no,None,5,may,1467,1,-1,0,None,yes,56-65,Low,no_no
2,41,technician,married,secondary,no,1270,yes,no,None,5,may,1389,1,-1,0,None,yes,36-45,Medium,no_yes
3,55,services,married,secondary,no,2476,yes,no,None,5,may,579,1,-1,0,None,yes,46-55,Medium,no_yes
4,54,admin.,married,tertiary,no,184,no,no,None,5,may,673,2,-1,0,None,yes,46-55,Low,no_no

In [57]:
query = "SELECT COUNT(*) AS total_customers FROM bank_customers"
pd.read_sql(query, conn)

   total_customers
0            11162

In [59]:
query = """
SELECT 
ROUND(
    100.0 * SUM(CASE WHEN deposit='yes' THEN 1 ELSE 0 END) / COUNT(*),
    2
) AS conversion_rate
FROM bank_customers
"""
pd.read_sql(query, conn)

   conversion_rate
0            47.38

In [61]:
query = """
SELECT ROUND(AVG(balance), 2) AS avg_balance
FROM bank_customers
"""
pd.read_sql(query, conn)

   avg_balance
0      1528.54

In [63]:
query = """
SELECT ROUND(AVG(age), 2) AS avg_age
FROM bank_customers
"""
pd.read_sql(query, conn)

   avg_age
0    41.23

In [65]:
query = """
SELECT
job,
COUNT(*) AS total_customers,
SUM(CASE WHEN deposit='yes' THEN 1 ELSE 0 END) AS conversions,
ROUND(
100.0 * SUM(CASE WHEN deposit='yes' THEN 1 ELSE 0 END)/COUNT(*),2
) AS conversion_rate
FROM bank_customers
GROUP BY job
ORDER BY conversion_rate DESC
"""
pd.read_sql(query, conn)

              job  total_customers  conversions  conversion_rate
0         student              360          269            74.72
1         retired              778          516            66.32
2      unemployed              357          202            56.58
3      management             2566         1301            50.70
4            None               70           34            48.57
5          admin.             1334          631            47.30
6   self-employed              405          187            46.17
7      technician             1823          840            46.08
8        services              923          369            39.98
9       housemaid              274          109            39.78
10   entrepreneur              328          123            37.50
11    blue-collar             1944          708            36.42

In [67]:
query = """
SELECT
marital,
COUNT(*) AS customers,
SUM(CASE WHEN deposit='yes' THEN 1 ELSE 0 END) AS conversions
FROM bank_customers
GROUP BY marital
"""
pd.read_sql(query, conn)

    marital  customers  conversions
0  divorced       1293          622
1   married       6351         2755
2    single       3518         1912

In [69]:
query = """
SELECT
education,
COUNT(*) AS customers,
SUM(CASE WHEN deposit='yes' THEN 1 ELSE 0 END) AS conversions
FROM bank_customers
GROUP BY education
"""
pd.read_sql(query, conn)

   education  customers  conversions
0       None        497          252
1    primary       1500          591
2  secondary       5476         2450
3   tertiary       3689         1996

In [71]:
query = """
SELECT
contact,
COUNT(*) AS customers,
SUM(CASE WHEN deposit='yes' THEN 1 ELSE 0 END) AS conversions
FROM bank_customers
GROUP BY contact
"""
pd.read_sql(query, conn)

     contact  customers  conversions
0       None       2346          530
1   cellular       8042         4369
2  telephone        774          390

In [73]:
query = """
SELECT
month,
COUNT(*) AS customers,
SUM(CASE WHEN deposit='yes' THEN 1 ELSE 0 END) AS conversions
FROM bank_customers
GROUP BY month
"""
pd.read_sql(query, conn)

   month  customers  conversions
0    apr        923          577
1    aug       1519          688
2    dec        110          100
3    feb        776          441
4    jan        344          142
5    jul       1514          627
6    jun       1222          546
7    mar        276          248
8    may       2824          925
9    nov        943          403
10   oct        392          323
11   sep        319          269

In [77]:
query = """
SELECT
[default],
loan,
housing,
COUNT(*) AS customers
FROM bank_customers
GROUP BY [default], loan, housing
ORDER BY customers DESC
"""
pd.read_sql(query, conn)

  default loan housing  customers
0      no   no      no       5209
1      no   no     yes       4382
2      no  yes     yes        812
3      no  yes      no        591
4     yes   no     yes         64
5     yes   no      no         47
6     yes  yes      no         34
7     yes  yes     yes         23